# Generated by Django 4.0.3 on 2022-03-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_category_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('out of delivery', 'Out Of Delivery'), ('delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
